export ZSH="/home/yunfan/.oh-my-zsh"
ZSH_THEME="dracula"
plugins=(
    git
    zsh-autosuggestions
    history-substring-search
    web-search
    wd
    z
    gitignore
    urltools
    catimg
    zsh_reload
)
source $ZSH/oh-my-zsh.sh
[ -f ~/.bash_user ] && . ~/.bash_user
[ -f ~/.zshrc_user ] && . ~/.zshrc_user
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
__conda_setup="$('/home/yunfan/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/yunfan/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/yunfan/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/yunfan/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
export TERM='xterm-256color'
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

#cuda settings
export CUDA_HOME=/usr/local/cuda
export PATH=${CUDA_HOME}/bin:${PATH}
export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:$LD_LIBRARY_PATH
