export ZSH="/home/yunfan/.oh-my-zsh"
ZSH_THEME="dracula"
plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
    web-search
    wd
    z
    gitignore
    urltools
    catimg
    zsh_reload
)
source $ZSH/oh-my-zsh.sh
if [ -f ~/.bash_user ]; then
    . ~/.bash_user
fi
if [ -f ~/.zshrc_user ]; then
    . ~/.zshrc_user
fi
__conda_setup="$('/home/yunfan/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/yunfan/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/yunfan/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/yunfan/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export TERM='xterm-256color'
